TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: '/media/zhong/1.0T/zhong_work/SlowFast/weights/SLOWFAST_32x2_R101_50_50.pkl'
#  CHECKPOINT_FILE_PATH: ""
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: True
#AVA:
#  DETECTION_SCORE_THRESH: 0.9
#  FRAME_DIR: '/media/zhong/1.0T/zhong_work/CVB/000058916v001/data/raw_frames'
#  FRAME_LIST_DIR: '/media/zhong/1.0T/zhong_work/CVB/000058916v001/data/ava_v2.2'
#  ANNOTATION_DIR: '/media/zhong/1.0T/zhong_work/CVB/000058916v001/data/ava_v2.2'
#  LABEL_MAP_FILE: 'behaviour_list.pbtxt'
#  GROUNDTRUTH_FILE: 'ava_val_set.csv'
#  TRAIN_GT_BOX_LISTS: ['ava_train_set.csv']
#  TRAIN_PREDICT_BOX_LISTS: [
#    "ava_train_predit_boxes.csv",
#    #"person_box_67091280_iou90/ava_detection_train_boxes_and_labels_include_negative_v2.2.csv",
#  ]
#  TEST_PREDICT_BOX_LISTS: ["ava_val_predit_boxes.csv"]

AVA:
  DETECTION_SCORE_THRESH: 0.8
  FRAME_DIR: '/media/zhong/1.0T/zhong_work/archive/rawframes_mini'
  FRAME_LIST_DIR: '/media/zhong/1.0T/zhong_work/archive/ava2.2_anno'
  ANNOTATION_DIR: '/media/zhong/1.0T/zhong_work/archive/ava2.2_anno'
  LABEL_MAP_FILE: 'behaviour_list.pbtxt'
  GROUNDTRUTH_FILE: 'ava_val_set.csv'
  TRAIN_GT_BOX_LISTS: ['ava_train_set.csv']
  TRAIN_PREDICT_BOX_LISTS: [
    "ava_train_predit_boxes.csv",
    #"person_box_67091280_iou90/ava_detection_train_boxes_and_labels_include_negative_v2.2.csv",
  ]
  TEST_PREDICT_BOX_LISTS: ["ava_val_predit_boxes.csv"]
  TRAIN_LISTS : ["train.csv"]

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[6, 13, 20], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 30
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15, 20]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 13
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 1
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
DEMO:
  ENABLE: False
  LABEL_FILE_PATH:  "/media/zhong/1.0T/zhong_work/SlowFast/demo/AVA/cattle.json"
#  WEBCAM: 0
  DETECTRON2_CFG: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  DETECTRON2_WEIGHTS: detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
  INPUT_VIDEO: "/media/zhong/1.0T/zhong_work/SlowFast/6.mp4"
  OUTPUT_FILE: "66.mp4"
#export PYTHONPATH=/media/zhong/1.0T/zhong_work/SlowFast/slowfast:$PYTHONPATH